### ISSUE TITLE
회원 탈퇴 후 재가입 시 이미지 로드 실패 

### ISSUE THREAD

**Issue by Jetom88** [f-lab-edu/eungeori#11]
### 📝개요 

- 회원가입 후 프로필을 변경한 뒤 탈퇴하고 다시 가입했을 때 프로필을 변경해도 변경 사항이 적용되지 않는 문제가 있습니다.

### ✅ To-do

- [ ] 원인 분석
   - [ ] 프로필 변경 로직 확인
   - [ ] 탈퇴 시 데이터 초기화 로직 확인
   - [ ] supabase의 auth.users에 데이터가 남아있는지 확인
- [ ] feat/middleware 브랜치 수정
   - [ ] 재가입 시 초기화된 상태인지 확인
- [ ] My page
  - [ ]  프로필 변경 로직 재검토 
  - [ ] 변경 시 정상 반영 확인
